import { Permission } from './roles.constants';

export const DEFAULT_MENU_ITEMS = [
  {
    title: 'Dashboard',
    icon: '<i class="fa-solid fa-chart-simple"></i>',
    route: '/panel/dashboard',
    requiredPermission: Permission.DASHBOARD_VIEW,
    order: 0,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
  },
  {
    title: 'Ventas',
    icon: '<i class="fa-solid fa-hand-holding-dollar"></i>',
    route: '/panel/ventas/clients',
    requiredPermission: Permission.INVOICE_READ,
    order: 1,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      // CLIENTS
      {
        title: 'Clientes',
        icon: 'people',
        route: '/panel/ventas/clients',
        requiredPermission: Permission.CLIENT_READ,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Nota Credito',
        icon: 'receipt',
        route: '/panel/ventas/notas-ajuste',
        requiredPermission: Permission.INVOICE_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      // INVOICES
      {
        title: 'Facturas Venta',
        icon: 'receipt',
        route: '/panel/ventas/comprobantes',
        requiredPermission: Permission.INVOICE_READ,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      // PRODUCTS
      // {
      //   title: 'Productos y Servicios',
      //   icon: 'inventory_2',
      //   route: '/panel/ventas/products_services',
      //   requiredPermission: Permission.PRODUCT_READ,
      //   order: 3,
      //   isActive: true,
      //   isVisible: true,
      //   metadata: { badge: null },
      // },
    ],
  },
  {
    title: 'Compras y Gastos',
    icon: '<i class="fa-solid fa-cart-shopping"></i>',
    route: '/panel/compras/purchases',
    requiredPermission: Permission.PURCHASE_READ,
    order: 2,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      // SUPPLIERS
      {
        title: 'Proveedores',
        icon: 'people_outline',
        route: '/panel/compras/proveedores',
        requiredPermission: Permission.PROVIDER_READ,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Nota Credito',
        icon: 'receipt',
        route: '/panel/compras/notas-ajuste',
        requiredPermission: Permission.PURCHASE_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      // INVOICES - PURCHASES
      {
        title: 'Facturas compra',
        icon: 'receipt',
        route: '/panel/compras/purchases',
        requiredPermission: Permission.PURCHASE_READ,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      // PRODUCTS PURCHASES
      // {
      //   title: 'Artículos',
      //   icon: 'inventory_2',
      //   route: '/panel/compras/articles',
      //   requiredPermission: Permission.PRODUCT_PURCHASE_READ,
      //   order: 3,
      //   isActive: true,
      //   isVisible: true,
      //   metadata: { badge: null },
      // },
    ],
  },
  {
    title: 'Articulos',
    icon: '<i class="fa-solid fa-boxes"></i>',
    route: '/panel/articles',
    requiredPermission: Permission.PRODUCT_READ,
    order: 3,
    isActive: true,
    isVisible: true,
    metadata: { badge: null },
  },
  {
    title: 'Nómina',
    icon: '<i class="fa-solid fa-file-invoice"></i>',
    route: '/panel/nomina/empleados',
    requiredPermission: Permission.NOMINA_ACCESS,
    order: 7,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      {
        title: 'Empleados',
        icon: 'people',
        route: '/panel/nomina/empleados',
        requiredPermission: Permission.NOMINA_EMPLOYEE_READ,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Períodos',
        icon: 'calendar_month',
        route: '/panel/nomina/periodos',
        requiredPermission: Permission.NOMINA_PERIOD_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Reportes',
        icon: 'bar_chart',
        route: '/panel/nomina/reportes',
        requiredPermission: Permission.NOMINA_REPORT_READ,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
    ],
  },
  {
    title: 'Pagos',
    icon: '<i class="fa-solid fa-money-bill-transfer"></i>',
    route: '/panel/pagos',
    requiredPermission: Permission.PAGO_READ,
    order: 4,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      {
        title: 'Cuentas por Cobrar',
        icon: 'arrow_downward',
        route: '/panel/pagos/cxc',
        requiredPermission: Permission.PAGO_READ,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Cuentas por Pagar',
        icon: 'arrow_upward',
        route: '/panel/pagos/cxp',
        requiredPermission: Permission.PAGO_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Vencimientos Cartera',
        icon: 'bar_chart',
        route: '/panel/pagos/aging',
        requiredPermission: Permission.PAGO_READ,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Movimientos',
        icon: 'swap_horiz',
        route: '/panel/pagos/movimientos',
        requiredPermission: Permission.PAGO_READ,
        order: 3,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
    ],
  },
  {
    title: 'Reportes',
    icon: '<i class="fa-solid fa-chart-line"></i>',
    route: '/panel/reports',
    requiredPermission: Permission.REPORT_VIEW,
    order: 5,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      {
        title: 'Reportes Generales',
        icon: '<i class="fa-solid fa-chart-line"></i>',
        route: '/panel/reports/reports-general',
        requiredPermission: Permission.REPORT_VIEW,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Reportes Cartera',
        icon: '<i class="fa-solid fa-chart-line"></i>',
        route: '/panel/reports/reports-cartera',
        requiredPermission: Permission.REPORT_VIEW,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Resumen Financiero',
        icon: '<i class="fa-solid fa-bar-chart"></i>',
        route: '/panel/reports/resumen',
        requiredPermission: Permission.REPORT_VIEW,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
    ],
  },
  {
    title: 'Contabilidad',
    icon: '<i class="fa-solid fa-book"></i>',
    route: '/panel/contabilidad',
    requiredPermission: Permission.ACCOUNTING_VIEW,
    order: 6,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      {
        title: 'Cuentas Contables',
        icon: '<i class="fa-solid fa-book-open"></i>',
        route: '/panel/contabilidad/cuentas-contables',
        requiredPermission: Permission.ACCOUNTING_VIEW,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Activos Fijos',
        icon: '<i class="fa-solid fa-calculator"></i>',
        route: '/panel/contabilidad/activos-fijos',
        requiredPermission: Permission.FIXED_ASSETS_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Bancos y Cajas',
        icon: '<i class="fa-solid fa-building-columns"></i>',
        route: '/panel/contabilidad/bancos',
        requiredPermission: Permission.ACCOUNTING_VIEW,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Comprobantes Contables',
        icon: '<i class="fa-solid fa-file-invoice-dollar"></i>',
        route: '/panel/contabilidad/comprobantes',
        requiredPermission: Permission.ACCOUNTING_VIEW,
        order: 3,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
    ],
  },
  {
    title: 'Administración',
    icon: '<i class="fa-solid fa-user-gear"></i>',
    route: '/panel/admin',
    requiredPermission: Permission.USER_MANAGE,
    order: 7,
    isActive: true,
    isVisible: true,
    other: 'NO',
    metadata: { badge: null },
    children: [
      {
        title: 'Usuarios',
        icon: '<i class="fa-solid fa-manage_accounts"></i>',
        route: '/panel/admin/users',
        requiredPermission: Permission.USER_MANAGE,
        order: 0,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Roles',
        icon: '<i class="fa-solid fa-shield"></i>',
        route: '/panel/admin/roles',
        requiredPermission: Permission.ROLE_READ,
        order: 1,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Gestion Menú',
        icon: '<i class="fa-solid fa-menu"></i>',
        route: '/panel/admin/menu',
        requiredPermission: Permission.MENU_MANAGE,
        order: 2,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
      {
        title: 'Configuración',
        icon: '<i class="fa-solid fa-settings"></i>',
        route: '/panel/admin/settings',
        requiredPermission: Permission.SETTINGS_VIEW,
        order: 3,
        isActive: true,
        isVisible: true,
        metadata: { badge: null },
      },
    ],
  },
];
